config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # temporarily removing range slider
  # concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  # Create the sign in and sign out routes (simply redirects to our auth endpoint), needed for redirecting on
  # cancancan access denied error
  devise_scope :user do
    delete 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "catalog#home"

  # Static Pages
  get '/about',      to: 'info#about',      as: 'about'
  get '/policies',   to: 'info#policies',   as: 'policies'
  get '/faq',        to: 'info#faq',        as: 'faq'
  get '/developers', to: 'info#developers', as: 'developers'
  get '/credits',    to: 'info#credits',    as: 'credits'

  # Mounting API endpoint at /api/v1/
  mount API => '/'

  # Collections routes
  resources :collections, only: [:index, :show], param: 'category_id', path: 'explore'

  # Blacklight routes
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  # Use singular resource with custom collection route to achieve:
  #   search_catalog_url = GET|POST /search |-> catalog#index
  resource :catalog, only: [], as: 'catalog', path: 'search', controller: 'catalog', constraints: { id: /.*/ } do
    collection do
      get '', action: :index
    end
    concerns :searchable
    # concerns :range_searchable
  end

  # OAI endpoint
  match :oai, to: 'catalog#oai', via: [:post, :get], as: :oai_catalog

  # Redirect for old download links
  get '/download/fedora_content/download/:uri/:block/:filename', to: 'assets#legacy_fedora_content', as: 'legacy_fedora_content',
    block: /(CONTENT|content)/, uri: /.+/, filename: /.+/

  # Routes for Solr Document using DOI as identifier
  #
  # Instead of specifying solr routes as:
  #   resources :solr_document, only: [:show], controller: 'catalog', path: 'doi', constraints: { id: /.*/ } do
  #     concerns :exportable
  #   end
  # Specifying routes using glob (*) in id param, this way slashes and period are accepted as part of the id.
  match 'doi/*id/download', to: 'assets#download', via: :get, as: 'content_download'
  match 'doi/*id/embed',    to: 'assets#embed',    via: :get, as: 'embed'
  match 'doi/*id/captions', to: 'assets#captions', via: :get, as: 'captions_download'
  match 'doi/*id',          to: 'catalog#show',    via: :get, as: :solr_document

  mount Blacklight::Engine => '/'

  # RESTful routes for reindex API, working around Blacklight route camping
  delete '/solr_documents/:id', to: 'solr_documents#destroy'
  put '/solr_documents/:id', to: 'solr_documents#update'
  get '/solr_documents/:id', to: 'solr_documents#show'

  resource :agreement

  resources :uploads, only: [:index, :new, :create], path: 'upload'

  get '/detail/:slug', to: 'featured_searches#show', as: 'featured_search'

  get 'myworks',             to: 'user#my_works'
  get 'account',             to: 'user#account'
  get 'unsubscribe_monthly', to: 'user#unsubscribe_monthly'

  get '/admin',                   to: 'admin#index',                 as: 'admin'

  namespace :admin do
    get 'author_affiliation_report/index'
    get 'author_affiliation_report/create'
    resources :request_agreements,  only: [:new, :create]
    resource  :alert_message,       only: [:edit, :update]
    resource  :site_configuration,  only: [:edit, :update]
    resources :deposits,            only: [:index, :show]
    resources :downloads,           only: :index
    resources :agreements,          only: :index
    resources :email_preferences
    resources :email_author_reports,     only: [:new, :create]
    resources :usage_statistics_reports, only: [:new, :create] do
      post 'email', on: :collection
    end
    resources :featured_searches, except: :show
    resource :contact_authors, only: [:new, :create]
  end

  # Resque web interface, only administrators have access
  # Make sure that the resque user restriction below is AFTER `devise_for :users`
  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: '/admin/resque'
  end

  get '/logs/all_author_monthly_reports_history', to: 'logs#all_author_monthly_reports_history'
  get '/logs/log_form',                           to: 'logs#log_form'
  get '/logs/ingest_history',                     to: 'logs#ingest_history'
  get '/download/download_log/:id',               to: 'logs#download_log', as: 'download_log'

  # Route used to render error page.
  get '/500', to: 'errors#internal_server_error'

  # Handle server redirects to /item/:id. This route will redirect those requests
  # to /catalog/:id.
  get '/item/:id',    to: 'catalog#legacy_show'
  get '/catalog/:id', to: 'catalog#legacy_show'

  # Temporary redirect for old deposit page url
  get '/deposit', to: redirect('/upload')
end

app/models/site_configuration.rb
# frozen_string_literal: true

# SiteConfiguration is a "Singleton" Model: only one record will ever exist in
# the database, and when more site configuration options are added, they will be
# added as columns for this single record.
# Access the Site Configuration object by calling SiteConfiguration::instance,
# like you would if accessing a typical singleton class in Ruby
class SiteConfiguration < ApplicationRecord
  SINGLETON_GUARD_VALUE = 0
  DOWNLOADS_DISABLED_MESSAGE_DEFAULT = 'Downloading has been temporarily disabled for Academic Commons. Contact an administrator for more information.' # rubocop:disable Layout/LineLength

  # The singleton_guard column is a unique column that must be set to 0
  # This ensures that only one record of type SiteConfiguration is ever created
  # (via https://stackoverflow.com/questions/399447/how-to-implement-a-singleton-model)
  validates :singleton_guard, inclusion: { in: [SINGLETON_GUARD_VALUE] }, presence: true
  validates :downloads_enabled, inclusion: { in: [true, false] }
  validates :deposits_enabled, inclusion: { in: [true, false] }

  # If there is no site configuration record in the database, we create one with
  # the default values in the block passed to first_or_create
  # todo : look into caching this in "The Rails Cache"
  def self.instance
    where(singleton_guard: 0).first_or_create! do |site_config|
      site_config.downloads_enabled = true
      site_config.downloads_message = DOWNLOADS_DISABLED_MESSAGE_DEFAULT
      site_config.deposits_enabled = true
      site_config.alert_message = ''
      site_config.singleton_guard = SINGLETON_GUARD_VALUE
    end
  end

  def self.downloads_enabled
    instance.downloads_enabled
  end

  def self.downloads_message
    return DOWNLOADS_DISABLED_MESSAGE_DEFAULT if instance.downloads_message == ''

    instance.downloads_message
  end

  def self.deposits_enabled
    instance.deposits_enabled
  end

  def self.alert_message
    instance.alert_message
  end
end

app/controllers/admin/site_configurations_controller.rb
# frozen_string_literal: true

module Admin
  class SiteConfigurationsController < AdminController
    load_and_authorize_resource class: SiteConfiguration

    def update
      if SiteConfiguration.instance.update(site_configuration_params)
        flash[:success] = 'Succesfully updated site option.'
        render :show, status: :ok
      else
        flash[:error] = 'There was an error updating the site option.'
        render :show, status: :unprocessable_entity
      end
    end

    private

    def site_configuration_params
      params.permit(:alert_message, :deposits_enabled, :downloads_enabled, :downloads_message)
    end
  end
end

app/helpers/site_configuration_helper.rb
# frozen_string_literal: true

module SiteConfigurationHelper
  def alert_message?
    SiteConfiguration.alert_message.present?
  end

  def downloads_enabled?
    SiteConfiguration.downloads_enabled
  end

  def deposits_enabled?
    SiteConfiguration.deposits_enabled
  end
end

app/views/admin/site_configurations/_alert_message_form.html.erb
<div id='alert-message-form'>
  <%= form_with url: admin_site_configuration_path, method: :patch, local: true do |form| %>
    <div>
      <%= form.text_area :alert_message, value: SiteConfiguration.alert_message %>
    </div>
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/site_configurations/_downloads_message_form.html.erb
<div class="mt-3" id='downloads-message-form'>
  <%= form_with url: admin_site_configuration_path, method: :patch, local: true, data: { turbo: false } do |form| %>
    <%= form.text_area :downloads_message, value: SiteConfiguration.downloads_message %>
    <%= form.submit 'Save Message', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/site_configurations/_toggle_deposits_form.html.erb
<div id='deposits-toggle-form'>
  <%= form_with url: admin_site_configuration_path, method: :patch, local: true, data: { turbo: false } do |form| %>
    <% if SiteConfiguration.deposits_enabled  %>
      <% action_label = "Disable Deposits" %>
      <% enable = false %>
    <% else %>
      <% action_label = "Enable Deposits" %>
      <% enable = true %>
    <% end %>
    <%= form.hidden_field :deposits_enabled, value: enable %>
    <%= form.submit action_label, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/site_configurations/_toggle_downloads_form.html.erb
<div id='downloads-toggle-form'>
  <%= form_with url: admin_site_configuration_path, method: :patch, local: true, data: { turbo: false } do |form| %>
    <% if SiteConfiguration.downloads_enabled  %>
      <% action_label = "Disable Downloads" %>
      <% enable = false %>
    <% else %>
      <% action_label = "Enable Downloads" %>
      <% enable = true %>
    <% end %>
    <div>
      <%= form.hidden_field :downloads_enabled, value: enable %>
      <%= form.submit action_label, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/site_configurations/edit.html.erb
<h2>Configure Site-wide Options</h3>

<div class="container">
  <h3>Enable and Set Alert Message (Currently <% if !SiteConfiguration.alert_message.blank? %>
      <span class="font-weight-bold text-success">Enabled</span>)
    <% else %>
      <span class="text-danger">Disabled</span>)
    <% end %>
  </h3>
  <p class="my-2">
    Administrators can set an alert message that will appear as a banner at the
    top of all pages on the Academic Commons site. If there is no alert message
    set, nothing will be displayed.
  </p>
  <%= render :partial=>'alert_message_form' %>
</div>

<hr class="mb-5">

<div class="container">
  <h3>Enable or Disable Asset Downloads (Currently <% if SiteConfiguration.downloads_enabled %>
          <strong class="text-success">Enabled</strong>)
        <% else %>
          <span class="font-weight-bold text-danger">Disabled</span>)
        <% end %>
  </h3>
  <p>
    In some situations, administrators may wish to disable downloads from the 
    Academic Commons site temporarily. When downloads are disabled, 'download' buttons will be
    replaced with a customizable message explaining that an admin has disabled this feature. 
  </p>
      <%= render :partial=>'toggle_downloads_form' %>
      <%= render :partial=>'downloads_message_form' %>
</div>

<hr class="mb-5">

<div class="container">
  <h3>Enable or Disable Self Deposits (Currently<% if SiteConfiguration.deposits_enabled %>
          <strong class="text-success">Enabled</strong>)
        <% else %>
          <span class="font-weight-bold text-danger">Disabled</span>)
        <% end %>
  </h3>
  <p>
    In some situations, administrators may wish to disable users from depositing 
    new materials to the Academic Commons site temporarily. When self-deposits are 
    disabled, all buttons and pages related to uploading will be hidden.
  </p>
  <%= render :partial=>'toggle_deposits_form' %>
</div>

app/views/admin/site_configurations/show.html.erb
<h2>Configure Site-wide Options</h3>

<div class="container">
  <h3>Enable and Set Alert Message (Currently <% if !SiteConfiguration.alert_message.blank? %>
      <span class="font-weight-bold text-success">Enabled</span>)
    <% else %>
      <span class="text-danger">Disabled</span>)
    <% end %>
  </h3>
  <p class="my-2">
    Administrators can set an alert message that will appear as a banner at the
    top of all pages on the Academic Commons site. If there is no alert message
    set, nothing will be displayed.
  </p>
  <%= render :partial=>'alert_message_form' %>
</div>

<hr class="mb-5">

<div class="container">
  <h3>Enable or Disable Asset Downloads (Currently <% if SiteConfiguration.downloads_enabled %>
          <strong class="text-success">Enabled</strong>)
        <% else %>
          <span class="font-weight-bold text-danger">Disabled</span>)
        <% end %>
  </h3>
  <p>
    In some situations, administrators may wish to disable downloads from the 
    Academic Commons site temporarily. When downloads are disabled, 'download' buttons will be
    replaced with a customizable message explaining that an admin has disabled this feature. 
  </p>
      <%= render :partial=>'toggle_downloads_form' %>
      <%= render :partial=>'downloads_message_form' %>
</div>

<hr class="mb-5">

<div class="container">
  <h3>Enable or Disable Self Deposits (Currently<% if SiteConfiguration.deposits_enabled %>
          <strong class="text-success">Enabled</strong>)
        <% else %>
          <span class="font-weight-bold text-danger">Disabled</span>)
        <% end %>
  </h3>
  <p>
    In some situations, administrators may wish to disable users from depositing 
    new materials to the Academic Commons site temporarily. When self-deposits are 
    disabled, all buttons and pages related to uploading will be hidden.
  </p>
  <%= render :partial=>'toggle_deposits_form' %>
</div>