config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # temporarily removing range slider
  # concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  # Create the sign in and sign out routes (simply redirects to our auth endpoint), needed for redirecting on
  # cancancan access denied error
  devise_scope :user do
    delete 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "catalog#home"

  # Static Pages
  get '/about',      to: 'info#about',      as: 'about'
  get '/policies',   to: 'info#policies',   as: 'policies'
  get '/faq',        to: 'info#faq',        as: 'faq'
  get '/developers', to: 'info#developers', as: 'developers'
  get '/credits',    to: 'info#credits',    as: 'credits'

  # Mounting API endpoint at /api/v1/
  mount API => '/'

  # Collections routes
  resources :collections, only: [:index, :show], param: 'category_id', path: 'explore'

  # Blacklight routes
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  # Use singular resource with custom collection route to achieve:
  #   search_catalog_url = GET|POST /search |-> catalog#index
  resource :catalog, only: [], as: 'catalog', path: 'search', controller: 'catalog', constraints: { id: /.*/ } do
    collection do
      get '', action: :index
    end
    concerns :searchable
    # concerns :range_searchable
  end

  # OAI endpoint
  match :oai, to: 'catalog#oai', via: [:post, :get], as: :oai_catalog

  # Redirect for old download links
  get '/download/fedora_content/download/:uri/:block/:filename', to: 'assets#legacy_fedora_content', as: 'legacy_fedora_content',
    block: /(CONTENT|content)/, uri: /.+/, filename: /.+/

  # Routes for Solr Document using DOI as identifier
  #
  # Instead of specifying solr routes as:
  #   resources :solr_document, only: [:show], controller: 'catalog', path: 'doi', constraints: { id: /.*/ } do
  #     concerns :exportable
  #   end
  # Specifying routes using glob (*) in id param, this way slashes and period are accepted as part of the id.
  match 'doi/*id/download', to: 'assets#download', via: :get, as: 'content_download'
  match 'doi/*id/embed',    to: 'assets#embed',    via: :get, as: 'embed'
  match 'doi/*id/captions', to: 'assets#captions', via: :get, as: 'captions_download'
  match 'doi/*id',          to: 'catalog#show',    via: :get, as: :solr_document

  mount Blacklight::Engine => '/'

  # RESTful routes for reindex API, working around Blacklight route camping
  delete '/solr_documents/:id', to: 'solr_documents#destroy'
  put '/solr_documents/:id', to: 'solr_documents#update'
  get '/solr_documents/:id', to: 'solr_documents#show'

  resource :agreement

  resources :uploads, only: [:index, :new, :create], path: 'upload'

  get '/detail/:slug', to: 'featured_searches#show', as: 'featured_search'

  get 'myworks',             to: 'user#my_works'
  get 'account',             to: 'user#account'
  get 'unsubscribe_monthly', to: 'user#unsubscribe_monthly'

  get '/admin',                   to: 'admin#index',                 as: 'admin'

  namespace :admin do
    get 'author_affiliation_report/index'
    get 'author_affiliation_report/create'
    resources :request_agreements,  only: [:new, :create]
    resource  :alert_message,       only: [:edit, :update]
    resource  :site_configuration,  only: [:edit, :update]
    resources :deposits,            only: [:index, :show]
    resources :downloads,           only: :index
    resources :agreements,          only: :index
    resources :email_preferences
    resources :email_author_reports,     only: [:new, :create]
    resources :usage_statistics_reports, only: [:new, :create] do
      post 'email', on: :collection
    end
    resources :featured_searches, except: :show
    resource :contact_authors, only: [:new, :create]
  end

  # Resque web interface, only administrators have access
  # Make sure that the resque user restriction below is AFTER `devise_for :users`
  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: '/admin/resque'
  end

  get '/logs/all_author_monthly_reports_history', to: 'logs#all_author_monthly_reports_history'
  get '/logs/log_form',                           to: 'logs#log_form'
  get '/logs/ingest_history',                     to: 'logs#ingest_history'
  get '/download/download_log/:id',               to: 'logs#download_log', as: 'download_log'

  # Route used to render error page.
  get '/500', to: 'errors#internal_server_error'

  # Handle server redirects to /item/:id. This route will redirect those requests
  # to /catalog/:id.
  get '/item/:id',    to: 'catalog#legacy_show'
  get '/catalog/:id', to: 'catalog#legacy_show'

  # Temporary redirect for old deposit page url
  get '/deposit', to: redirect('/upload')
end

app/helpers/catalog_helper.rb
require 'academic_commons'

module CatalogHelper
  include Blacklight::CatalogHelperBehavior
  include ApplicationHelper

  delegate :repository, to: :controller

  # Adds handle or doi prefix if necessary. Makes field a clickable link.
  def link_identifier(**options)
    value = options[:value].is_a?(Array) ? options[:value].first : options[:value]
    url = AcademicCommons.identifier_url(value)
    [link_to(url, url)]
  end

  # Combines title and part number for series. Used on item page.
  def combine_title_and_part_number(**options)
    field = options[:field]
    part_number_field = field.gsub('_ssim', '_part_number_ssim')
    part_numbers = options[:document].fetch(part_number_field, [])
    options.fetch(:value, []).zip(part_numbers).map do |title, part_number|
      facet_params = search_state.reset.filter(field).add(title).params
      value = link_to title, search_action_path(facet_params)

      value.concat(", #{part_number}") unless part_number == 'NONE'
      value
    end
  end

  def date_format(**options)
    options[:value].map do |v|
      # convert to a date time object and then format date
      Time.zone.parse(v).strftime('%B %-d, %Y')
    end
  end

  # transforms related item label information
  def related_item_relation_label(related_item)
    related_item[:relation_type].sub('isNewVersionOf', 'Previous version').sub('isPreviousVersionOf', 'Subsequent version').remove(/^is/).underscore.gsub('_', ' ').upcase_first.concat(':')
  end

  # Wraps spans around each value.
  def wrap_in_spans(**options)
    safe_join(options.fetch(:value, []).map { |v| content_tag(:span, html_escape(v)) })
  end

  # Render values as metatags. Not displayed on the page, but are visible to search engines.
  def metatags(**options)
    itemprop = options.dig(:config, :itemprop)
    safe_join(
      options.fetch(:value, []).map { |v| content_tag(:meta, nil, itemprop: itemprop, content: v) }
    )
  end

  # TODO: Move to a browse controller
  def collect_facet_field_values(facet_field_results)
    results = {}
    facet_field_results.each do |facet_field, facet_counts|
      results[facet_field] = (0...facet_counts.length/2).map do |ix|
        { name: facet_counts[ix * 2], count: facet_counts[1 + ix * 2] }
      end
    end
    results
  end

  # TODO: Move to a browse controller
  def single_facet_values(facet_field)
    query_params = { q: '', rows: '0', 'facet.limit'=> -1, 'facet.field' => facet_field}
    solr_results = repository.search(query_params)
    facet_field_results = solr_results.facet_counts['facet_fields']
    collect_facet_field_values(facet_field_results).fetch(facet_field,[])
  end

  def get_metadata_list(doc)
    #catch any error and return an error message that resources are unavailable
    #this prevents fedora server outages from making ac2 item page inaccessible
    begin
      #TODO: is this side effect on doc necessary?
      doc['object_display'] = [ "#{fedora_config["url"]}" + '/objects/' + doc['id'] + '/methods' ]
      results = doc['described_by_ssim'].map do |ds_uri|
        res = {}
        pid = ds_uri.split('/')[1]
        dsid = ds_uri.split('/')[2]
        # res[:id] = pid is not used
        # res[:title] = 'description' is not used
        # constant suffix for backwards compatibility with AC2
        filename = "#{pid.gsub(/\:/,'')}_description.xml"
        res[:show_url] = fedora_content_path(:show_pretty, pid, dsid, filename)
        res[:download_url] = fedora_content_path(:download, pid, dsid, filename)
        res
      end
    rescue => e
      Rails.logger.error "In get_metadata_list: #{e.message}"
      results = []
    end

    return results
  end

  def exclusive_feature_search?(feature)
    return false if params[:q].present? || params.fetch(:f, {}).keys.length > 1

    params.dig(:f, :featured_search) == [feature.slug]
  end

  ############### Copied from Blacklight CatalogHelper #####################

  def itemscope_itemtype
    url_from_map = blacklight_config[:itemscope][:itemtypes][@document['genre_ssim']]
    if url_from_map.nil?
      'http://schema.org/CreativeWork'
    else
      url_from_map
    end
  end
end

app/views/catalog/_asset_buttons.html.erb
<% assets = @document.assets %>

<% if @document.restricted? %>
  <p><em><%= @document.access_restriction %></em></p>
<% elsif @document.embargoed? %>
  <p><em><%= t('blacklight.search.show.assets.embargoed', date: @document[:free_to_read_start_date_ssi]) %></em></p>
<% elsif not downloads_enabled? %>
  <p class="bg-secondary text-white"><%= SiteConfiguration.downloads_message %></p>
<% elsif assets.count == 1 %>
  <% if assets.first.playable? %>

    <% if false %>
      <%= link_to t('blacklight.tools.play_button'), assets.first.download_path, class: 'btn btn-primary play-button', 'aria-label': 'Play file' %>
    <% end %>

  <% end %>

<%= link_to t('blacklight.tools.download_button'), assets.first.download_path, class: 'btn btn-primary download-button', 'aria-label': 'Download file', data: { turbo: false } %>
<% else %>
  <% if assets.any?(&:playable?) %>

    <% if false %>
      <a href="#assets-panel" class="btn btn-primary play-button scroll" aria-label="Play file"><%= t('blacklight.tools.play_button') %></a>
    <% end %>

  <% end %>

  <a href="#assets-panel" class="btn btn-primary download-button scroll" aria-label="Download file"><%= t('blacklight.tools.download_button') %></a>
<% end %>

app/views/catalog/_doi.html.erb
<h3>D O I</h3>
<label for="doi" class="doi-label">DOI</label>
<input type="text" id="doi" value="<%= @document.full_doi %>" readonly>
<button class="btn copy-to-clipboard" type="button" data-clipboard-target="#doi" aria-label="Copy DOI to clipboard">
  <i class="fas fa-paste" title="Copy DOI to clipboard" aria-hidden="true"></i>
  <span class="visually-hidden">Copy DOI to clipboard</span>
</button>

app/views/catalog/_download_and_doi.erb
<%= render partial: 'download_button' %>

<div class="doi-container">
  <label for="doi" class="doi-label">DOI</label>
  <div class="doi-and-copy-button">
    <textarea rows="1" readonly onclick="this.focus();this.select()" id="doi" title="<%= @document.full_doi %>"><%= @document.full_doi %></textarea>
    <button class="btn copy-to-clipboard" type="button" data-clipboard-target="#doi" aria-label="Copy DOI to clipboard">
      <i class="fas fa-paste" title="Copy DOI to clipboard" aria-hidden></i>
      <span class="visually-hidden">Copy DOI to clipboard</span>
    </button>
  </div>
</div>

app/views/catalog/_download_button.erb
<% assets = @document.assets %>

<% if @document.restricted? %>
  <p><em><%= @document.access_restriction %></em></p>
<% elsif @document.embargoed? %>
  <p><em><%= t('blacklight.search.show.assets.embargoed', date: @document[:free_to_read_start_date_ssi]) %></em></p>
<% elsif assets.count == 1 %>
  <%= link_to t('blacklight.tools.download_button'), assets.first.download_path, class: 'btn btn-primary download-button', 'aria-label': 'Download file' %>
<% else %>
  <a href="#assets-panel" class="btn btn-primary download-button scroll" aria-label="Download file"><%= t('blacklight.tools.download_button') %></a>
<% end %>

app/views/catalog/_home_text.html.erb
<div id="home-content">

<p><%= current_user %></p>
  <p class="summary">
    <strong>Academic Commons</strong> provides global access to research and scholarship produced at Columbia University and its affiliate institutions. <a href="/about/" aria-label="Learn more about Academic Commons">Learn more &rarr;</a>
  </p>

  <div class="row menu homepage-menu">
      <%= link_to collections_path, class: 'col-md-6 tile collections' do %>
        <div class="top">
          <%= svg 'icon-browse' %>
          <h2>Explore the Repository</h2>
        </div>
        <p>Discover what researchers and scholars are sharing in Academic Commons. Browse highlighted contributions from across Columbia and its affiliate institutions.</p>
      <% end %>
    <% if deposits_enabled? %>
      <a href="/upload" class="col-md-6 tile upload">
        <div class="top">
          <%= svg 'icon-upload' %>
          <h2>Upload Your Research</h2>
        </div>
        <p>Are you a member of the Columbia community? Want your research to be more discoverable and accessible? Upload it to Academic Commons today.</p>
      </a>
    <% end %>
  </div>

  <div class="row homepage-info">
    <% cache('repository_statistics', expires_in: 1.day, race_condition_ttl: 2, skip_digest: true) do %>
      <div class="stats col-md-4">
        <h3>Stats at a glance</h3>
        <ul>
          <li><span><%= counts[:all] %></span> <%= link_to('total works', search_action_path) %></li>
          <li><span><%= counts[:articles] %></span> <%= link_to('articles', type_search('Articles')) %></li>
          <li><span><%= counts[:reports] %></span> <%= link_to('reports', type_search('Reports')) %></li>
          <li><span><%= counts[:doctoral_theses] %></span> <%= link_to('doctoral theses', dissertation_search) %></li>
          <li><span><%= counts[:conference_materials] %></span> <%= link_to('conference materials', type_search('Conference Objects')) %></li>
          <li><span><%= counts[:datasets] %></span> <%= link_to('datasets', type_search("Data (Information)")) %></li>
        </ul>
      </div>
    <% end %>

    <div class="quotes col-md-8">
      <blockquote>
        “Academic Commons is an important way that Columbia makes our scholarship accessible and discoverable. Open access has been incredibly effective in helping my writing reach new and important audiences.”
        <footer><span>Sharon Marcus</span> Orlando Harriman Professor of English, Columbia University</footer>
      </blockquote>
      <blockquote>
        “Academic Commons has enabled us to distribute citable versions of <em>all</em> our work, including software products. It tracks how much the software is being accessed, which helps us show the impact of our work.”
        <footer><span>Simon J. Mason</span> Senior Research Scientist, International Research Institute for Climate and Society</footer>
      </blockquote>
      <blockquote>
        “The publication process takes time. I use Academic Commons to share my findings with the larger community so the knowledge and insights I produce can be used sooner.”
        <footer><span>Oren Pizmony-Levy</span> Associate Professor of International and Comparative Education, Teachers College</footer>
      </blockquote>
    </div>
  </div>

</div><!-- #home-content -->

app/views/catalog/_show_assets.html.erb
<% asset_docs = document.assets %>

<div id="assets-panel" class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"><%= t('blacklight.search.show.panels.files') %></h2>
  </div>
    <% if document.restricted? %>
      <p><em><%= document.access_restriction %></em></p>
    <% elsif document.embargoed? %>
      <p><em><%= t('blacklight.search.show.assets.embargoed', date: document[:free_to_read_start_date_ssi]) %></em></p>
    <% elsif not downloads_enabled? %>
      <p><em><%= SiteConfiguration.downloads_message %></em></p>
    <% elsif asset_docs.present? %>
      <% asset_docs.each do |asset| %>
        <ul class="list-group">
          <li class="list-group-item">
            <span class="image"><%= image_tag asset.thumbnail, height: 100, alt: "thumbnail for #{asset.filename}" %></span>
            <span class="filename"><%= asset.filename %></span>
            <span class="mimetype"><%= asset.fetch(:downloadable_content_type_ssi, nil) %></span>
            <span class="filesize"><%= number_to_human_size(asset.fetch(:downloadable_content_size_isi, nil)) %></span>
            <% if asset.playable? %>
              <span class="icon play"><%= link_to ('<span class="far fa-play-circle" aria-hidden="true" title="Play"></span><span class="visually-hidden">Play</span>').html_safe, "#play-collapse-#{asset.id.gsub(/\/|\./, '-')}", data: { toggle: 'collapse' } %></span>
            <% end %>
            <span class="icon download"><%= link_to ('<span class="far fa-arrow-alt-circle-down" aria-hidden="true" title="Download file"></span><span class="visually-hidden">Download File</span>').html_safe, asset.download_path, data: { turbo: false } %></span>
          </li>
        </ul>
        <% if asset.playable? %>
          <div class="collapse media-player-container" id="<%= "play-collapse-#{asset.id.gsub(/\/|\./, '-')}" %>">
            <%= player(asset, solr_document_url(document.doi)) %>
            <button class="btn btn-link btn-sm embed-link" data-toggle="modal" data-target="#<%= "embed-code-modal-#{asset.id.gsub(/\/|\./, '-')}" %>"><i class="fas fa-code"></i> Embed</button>
              <%=
                modal("embed-code-modal-#{asset.id.gsub(/\/|\./, '-')}", "md", "Embed Player") do
                  tag.textarea onclick: 'this.focus();this.select()', class: 'embed-code', rows: '4' do
                  "<iframe title=\"Academic Commons media player\" width=\"560\" height=\"315\" src=\"#{embed_url(asset.id)}\" frameborder=\"0\" allowfullscreen></iframe>"
                end
              end
            %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p><em><%= t('blacklight.search.show.assets.unavailable') %></em></p>
    <% end %>
  </ul>
</div>

app/views/catalog/_show_default.html.erb
<%#
  Overriding Blacklight v6.14.1 template.

  - Adding our own customized panels to re-organize the item page.
  - Separate sections for basic record information, subject (which are
    organized in tables), files (assets), more information, and notes.
%>
<div style='border: solid green'>
<h1>Show default!!</h1>

<% doc_presenter = document_presenter(document) %>

<%# Render tags above title %>
<p class="genre-labels">
<% doc_presenter.fields_to_render().select { |name, f| f[:display] == :tag }.each do |field_name, field| -%>
  <span class="tag-label"><%= doc_presenter.field_value field %></span>
<% end -%>
</p>

<%# Render title %>
<%= content_tag(:h1, document_presenter(@document).html_title, itemprop: "name") %>

<%# Render author and abstract %>
<% doc_presenter.fields_to_render().select { |name, f| f[:display] == :main_content }.each do |field_name, field| -%>
  <p class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field %></p>
<% end -%>

<%# Render table fields %>
<% doc_presenter.fields_to_render().select { |name, f| f[:display] == :table }.each do |field_name, field| -%>
  <div class="subjects">
    <h2><%= field.label %></h2>
    <ul>
      <% doc_presenter.field_value(field, join: false).each do |value| %>
        <li><%= value %></li>
      <% end %>
    </ul>
  </div>
<% end -%>

<%# Render asset information %>
<%= render 'show_assets', document: document %>

<%# Render also published in %>
<% if doc_presenter.fields_to_render().any? { |name, f| f[:display] == :published_in } -%>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title"><%= t('blacklight.search.show.panels.published_in') %></h2>
    </div>
    <div class="panel-body">
      <dl>
        <% doc_presenter.fields_to_render().select { |name, f| f[:display] == :published_in }.each do |field_name, field| -%>
          <dt><%= field.label %></dt>
          <% doc_presenter.field_value(field, join: false).each do |value| %>
            <dd><%= value %></dd>
          <% end %>
        <% end -%>
      </dl>
    </div>
  </div>
<% end %>

<%# Render more about this work %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"><%= t('blacklight.search.show.panels.more_info') %></h2>
  </div>
  <div class="panel-body">
    <dl>
      <% doc_presenter.fields_to_render().select { |name, f| f[:display].blank? }.each do |field_name, field| -%>
        <dt><%= field.label %></dt>
        <% doc_presenter.field_value(field, join: false).each do |value| %>
          <dd><%= value %></dd>
        <% end %>
      <% end -%>
    </dl>
  </div>
</div>

<%# Render related items %>
<%= render 'show_related_items', document: document %>

<%# Render note %>
<% note_text = [] -%>
<% doc_presenter.fields_to_render().select { |name, f| f[:display] == :notes }.each do |field_name, field| -%>
  <% doc_presenter.field_value(field, join: false).each { |v| note_text << v } %>
<% end -%>

<% if note_text.present? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title"><%= t('blacklight.search.show.panels.notes') %></h2>
    </div>
    <div class="panel-body">
      <% note_text.each do |text| %>
        <p><%= text %></p>
      <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/catalog/_show_main_content.html.erb
<%# 
  Overriding Blacklight v8.12.3 partial -  this renders the Document viewComponent instead of calling render_document_partials

  show_main_content is what is rendered when viewing an individual document (this partial is rendered by the BL 8 catalog/show view)

  - remove rendering of page header component (with prev/next displays)
  - 
 %>

<% @page_title = t('blacklight.search.show.title', document_title: document_presenter(@document).html_title, application_name: application_name).html_safe %>
<% content_for(:head) { render_link_rel_alternates } %>

<div id="document" class="document <%= render_document_class %>" itemscope  itemtype="<%= @document.itemtype %>">
  <div id="doc_<%= @document.id.to_s.parameterize %>">
    
    <% document_component = blacklight_config.view_config(:show).document_component -%>
    <%= render (document_component).new(document: document_presenter(@document), component: :div, show: true, partials: blacklight_config.view_config(:show).partials) do |component| %>
      <% component.with_title(as: 'h1', classes: '', link_to_document: false, actions: false) %>
      <% component.with_footer do %>
        <% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
          <!-- COinS, for Zotero among others. -->
          <span class="Z3988" title="<%= @document.export_as_openurl_ctx_kev(document_presenter(@document).display_type) %>"></span>
        <% end %>
      <% end %>
    <% end %>
  
  </div>
</div>

app/views/catalog/_show_related_items.html.erb
<div style='border: solid red'>
<h1>Show related items!</h1>

<% related_items = document.related_items %>

<% if related_items.present? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title"><%= t('blacklight.search.show.panels.related_items') %></h2>
    </div>
    <div class="panel-body">
      <dl>
        <% related_items.each do |related_item| -%>
          <dt><%= related_item_relation_label(related_item) %></dt>
          <dd><%= link_to related_item[:title], related_item[:link], target: '_blank' %></dd>
        <% end %>
      </dl>
    </div>
  </div>
<% end %>
</div>

app/views/catalog/_social_buttons.html.erb
<h3>social media buttons!</h3>

<a class="twitter-button" href="https://twitter.com/intent/tweet?text=<%= @document.full_doi %>"><i title="Share to Twitter" class="fab fa-twitter-square"></i></a>

<a class="facebook-button" href="https://www.facebook.com/sharer/sharer.php?u=<%= @document.full_doi %>"><i title="Share to Facebook" class="fab fa-facebook-square"></i></a>

<a class="email-button" href="mailto:?subject=<%= @document.title %>&body=<%= @document.full_doi %>"><i title="Share to Email" class="fas fa-envelope-square"></i></a>

app/views/catalog/_use_and_reproduction.erb
<%= use_and_reproduction_display(
  document.fetch(:use_and_reproduction_uri_ssim, []).first) %>

app/views/catalog/_use_and_reproduction.html.erb
<h3> use and reproduction!</h3>
<%= use_and_reproduction_display(
  document.fetch(:use_and_reproduction_uri_ssim, []).first) %>

app/views/catalog/home.html.erb
<div id="content" class="col-md-12">
  <%= render partial: 'home_text' %>

  <%= render 'shared/sitelinks_search_box' %>
</div>

app/views/catalog/index.html.erb
<%#
  Overriding Blacklight v8 template.

  - removes facet sidenav from front page
  - removes homepage conditional logic, homepage moved to its own template
  - render view components for sidebar (instead of overriding partials, during pre-Blacklight 8)
    based on the configuration in app/controllers/catalog_controller.rb

%>
<% content_for(:head) do %>
  <meta name="blacklight-search-storage" content="<%= blacklight_config.track_search_session.storage %>">
<% end %>


<%# 
    We used to render the BL7 _search_sidebar partial,
        which rendered the _facets partial,
        which rendered the _facet_group partial,
        which renders the facet_group's viewComponent

    Now, we simply render the BL 8 sidebar component, which reads our config
    and displays the facets as expected.
%>

<div id="sidebar" class="<%= sidebar_classes %>">
  <% conf = blacklight_config.view_config(document_index_view_type) %>
  <%= render conf.sidebar_component.new(blacklight_config: blacklight_config,
                                        response: @response,
                                        view_config: conf) %>
</div>

<div id="content" class="<%= main_content_classes %>">
  <%= render :partial=>'/shared/featured_searches' %>
  <%= render 'search_results' %>
</div>