config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # temporarily removing range slider
  # concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  # Create the sign in and sign out routes (simply redirects to our auth endpoint), needed for redirecting on
  # cancancan access denied error
  devise_scope :user do
    delete 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "catalog#home"

  # Static Pages
  get '/about',      to: 'info#about',      as: 'about'
  get '/policies',   to: 'info#policies',   as: 'policies'
  get '/faq',        to: 'info#faq',        as: 'faq'
  get '/developers', to: 'info#developers', as: 'developers'
  get '/credits',    to: 'info#credits',    as: 'credits'

  # Mounting API endpoint at /api/v1/
  mount API => '/'

  # Collections routes
  resources :collections, only: [:index, :show], param: 'category_id', path: 'explore'

  # Blacklight routes
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  # Use singular resource with custom collection route to achieve:
  #   search_catalog_url = GET|POST /search |-> catalog#index
  resource :catalog, only: [], as: 'catalog', path: 'search', controller: 'catalog', constraints: { id: /.*/ } do
    collection do
      get '', action: :index
    end
    concerns :searchable
    # concerns :range_searchable
  end

  # OAI endpoint
  match :oai, to: 'catalog#oai', via: [:post, :get], as: :oai_catalog

  # Redirect for old download links
  get '/download/fedora_content/download/:uri/:block/:filename', to: 'assets#legacy_fedora_content', as: 'legacy_fedora_content',
    block: /(CONTENT|content)/, uri: /.+/, filename: /.+/

  # Routes for Solr Document using DOI as identifier
  #
  # Instead of specifying solr routes as:
  #   resources :solr_document, only: [:show], controller: 'catalog', path: 'doi', constraints: { id: /.*/ } do
  #     concerns :exportable
  #   end
  # Specifying routes using glob (*) in id param, this way slashes and period are accepted as part of the id.
  match 'doi/*id/download', to: 'assets#download', via: :get, as: 'content_download'
  match 'doi/*id/embed',    to: 'assets#embed',    via: :get, as: 'embed'
  match 'doi/*id/captions', to: 'assets#captions', via: :get, as: 'captions_download'
  match 'doi/*id',          to: 'catalog#show',    via: :get, as: :solr_document

  mount Blacklight::Engine => '/'

  # RESTful routes for reindex API, working around Blacklight route camping
  delete '/solr_documents/:id', to: 'solr_documents#destroy'
  put '/solr_documents/:id', to: 'solr_documents#update'
  get '/solr_documents/:id', to: 'solr_documents#show'

  resource :agreement

  resources :uploads, only: [:index, :new, :create], path: 'upload'

  get '/detail/:slug', to: 'featured_searches#show', as: 'featured_search'

  get 'myworks',             to: 'user#my_works'
  get 'account',             to: 'user#account'
  get 'unsubscribe_monthly', to: 'user#unsubscribe_monthly'

  get '/admin',                   to: 'admin#index',                 as: 'admin'

  namespace :admin do
    get 'author_affiliation_report/index'
    get 'author_affiliation_report/create'
    resources :request_agreements,  only: [:new, :create]
    resource  :alert_message,       only: [:edit, :update]
    resource  :site_configuration,  only: [:edit, :update]
    resources :deposits,            only: [:index, :show]
    resources :downloads,           only: :index
    resources :agreements,          only: :index
    resources :email_preferences
    resources :email_author_reports,     only: [:new, :create]
    resources :usage_statistics_reports, only: [:new, :create] do
      post 'email', on: :collection
    end
    resources :featured_searches, except: :show
    resource :contact_authors, only: [:new, :create]
  end

  # Resque web interface, only administrators have access
  # Make sure that the resque user restriction below is AFTER `devise_for :users`
  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: '/admin/resque'
  end

  get '/logs/all_author_monthly_reports_history', to: 'logs#all_author_monthly_reports_history'
  get '/logs/log_form',                           to: 'logs#log_form'
  get '/logs/ingest_history',                     to: 'logs#ingest_history'
  get '/download/download_log/:id',               to: 'logs#download_log', as: 'download_log'

  # Route used to render error page.
  get '/500', to: 'errors#internal_server_error'

  # Handle server redirects to /item/:id. This route will redirect those requests
  # to /catalog/:id.
  get '/item/:id',    to: 'catalog#legacy_show'
  get '/catalog/:id', to: 'catalog#legacy_show'

  # Temporary redirect for old deposit page url
  get '/deposit', to: redirect('/upload')
end

app/models/user.rb
class User < ApplicationRecord
  # Connects this user object to Blacklights Bookmarks and Folders.
  include Blacklight::User

  # User information is updated before every save and before validation when an
  # object is created. We have to explicitly make the two calls because on
  # create validation will fail if email, etc are not present. Every time a user
  # logs in and logs out their user model is saved by devise. Therefore, ldap
  # information is updated at user log in and log out.
  before_validation :set_personal_info_via_ldap, on: :create
  before_save       :set_personal_info_via_ldap

  # Configure devise for our User model
  devise :rememberable, :trackable, :omniauthable, omniauth_providers: Devise.omniauth_configs.keys

  ADMIN = 'admin'.freeze
  ROLES = [ADMIN].freeze

  has_many :agreements, dependent: :destroy
  has_many :deposits,   dependent: :nullify # Keep deposits even if the user has been removed.

  def self.admins
    where(role: ADMIN)
  end

  def admin?
    role == ADMIN
  end

  def to_s
    full_name
  end

  # Use uni as full_name in case an ldap entry can't be found and thus no
  # first name or last name can be retrieved.
  def full_name
    first_name.present? && last_name.present? ? "#{first_name} #{last_name}" : uid
  end

  def set_personal_info_via_ldap
    return if uid.blank?

    # Set email, in case ldap query fails or there isn't an ldap record for this user.
    self.email = "#{uid}@columbia.edu" if email.blank?

    begin
      ldap = Cul::LDAP.new
      person = ldap.find_by_uni(uid)

      if person
        # Don't override with nil
        self.email      = person.email || email
        self.first_name = person.first_name || first_name
        self.last_name  = person.last_name || last_name

        Rails.logger.info "Retrived user information via LDAP for #{full_name} (#{uid})"
      else
        Rails.logger.warn "LDAP record for #{uid} NOT found."
      end
    rescue StandardError => e
      raise e if new_record?
    end
  end

  def signed_latest_agreement?
    agreements.map(&:agreement_version).include?(Agreement::LATEST_AGREEMENT_VERSION)
  end

  def email_preference
    @email_preference ||= EmailPreference.for(uid)
    @email_preference ||= EmailPreference.create(uni: uid, email: email, unsubscribe: false)
    @email_preference
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, except: :unsubscribe_monthly

  layout 'dashboard'

  def account
    @email_preference = current_user.email_preference
    @user_api_token = user_api_token || Token.new
  end

  def my_works
    @pending_works = pending_works
    @embargoed_works = embargoed_works
    @current_works_with_stats = current_works_with_stats
  end

  def unsubscribe_monthly
    author_id = params[:author_id].to_s

    begin
      raise 'Request missing parameters.' if author_id.blank? || params[:chk].blank?
      raise 'Cannot be verified.' unless Rails.application.message_verifier(:unsubscribe).verify(params[:chk]) == author_id

      epref = EmailPreference.find_or_initialize_by(uni: author_id)
      epref.unsubscribe = true
      epref.save!

      flash[:success] = 'Unsubscribe request successful'
    rescue StandardError
      flash[:error] = 'There was an error with your unsubscribe request'
    end

    redirect_to root_url
  end

  private

  def pending_works
    return [] if current_user.deposits.blank?

    identifiers = current_user.deposits.map(&:hyacinth_identifier).compact

    if identifiers.present?
      results = AcademicCommons.search do |params|
        identifiers = identifiers.map { |i| "\"#{i}\"" }.join(' OR ')
                                 .prepend('(').concat(')')
        params.filter('fedora3_pid_ssi', identifiers)
        params.aggregators_only
        params.field_list('fedora3_pid_ssi')
      end

      hyacinth_ids_in_ac = results.documents.map { |d| d[:fedora3_pid_ssi] }
    else
      hyacinth_ids_in_ac = []
    end

    current_user.deposits.to_a.keep_if do |deposit|
      hyacinth_id = deposit.hyacinth_identifier
      hyacinth_id.blank? || !hyacinth_ids_in_ac.include?(hyacinth_id)
    end
  end

  def embargoed_works
    AcademicCommons.search do |params|
      params.filter('author_uni_ssim', current_user.uid)
      params.embargoed_only
      params.aggregators_only
    end
  end

  def current_works_with_stats
    options = {
      start_date:  Date.current.prev_month.beginning_of_month,
      end_date:    Date.current.prev_month.end_of_month,
      solr_params: { q: nil, fq: ["author_uni_ssim:\"#{current_user.uid}\""] }
    }
    AcademicCommons::Metrics::UsageStatistics.new(**options)
                                             .calculate_lifetime
                                             .calculate_period
  end

  def user_api_token
    Token.find_by(authorizable: current_user, scope: Token::API)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

require 'omniauth/cul'

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  # The CAS login redirect to the columbia_cas callback endpoint AND the developer form submission to the
  # developer_uid callback do not send authenticity tokens, so we'll skip token verification for these actions.
  skip_before_action :verify_authenticity_token, only: [:columbia_cas, :developer_uid]

  # POST /users/auth/developer_uid/callback
  def developer_uid
    return unless Rails.env.development? # Only allow this action to run in the development environment

    uid = params[:uid]
    user = User.find_by(uid: uid)

    unless user
      flash[:alert] = "Login attempt failed.  User #{uid} does not have an account."
      redirect_to root_path
      return
    end

    flash[:success] = 'You have succesfully logged in.'
    sign_in_and_redirect user, event: :authentication # this will throw if user is not activated
  end

  # POST /users/auth/columbia_cas/callback
  def columbia_cas # rubocop:disable Metrics/AbcSize
    callback_url = user_columbia_cas_omniauth_callback_url # The columbia_cas callback route in this application
    uid, _affils = Omniauth::Cul::ColumbiaCas.validation_callback(request.params['ticket'], callback_url)

    user = User.find_by(uid: uid) || User.create(uid: uid, email: "#{uid}@columbia.edu")
    flash[:success] = 'You have succesfully logged in.'
    sign_in_and_redirect user, event: :authentication
  rescue Omniauth::Cul::Exceptions::Error => e
    # If an unexpected CAS ticket validation occurs, log the error message and ask the user to try
    # logging in again.  Do not display the exception object's original message to the user because it may
    # contain information that only a developer should see.
    error_message = 'CAS login validation failed. Please try again.'
    Rails.logger.debug(error_message + "  #{e.class.name}: #{e.message}")
    flash[:alert] = error_message
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :set_return_to, only: :new

  # This allows us to use 'redirect_to new_user_session_path' to render a form
  # that sends a POST req to our omniauth endpoint (this is the secure way and
  # POST is not possible with redirect_to)
  # inspiration: https://stackoverflow.com/questions/985596/redirect-to-using-post-in-rails
  def new # rubocop:disable Lint/UselessMethodDefinition
    super
  end

  # This is needed if not using database authenticable (see https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview#using-omniauth-without-other-authentications)
  def new_session_path(scope)
    new_user_session_path # this accomodates Users namespace of the controller
  end

  private

  def set_return_to
    session[:return_to] =
      if request.referer
        URI.parse(request.referer).path
      else
        root_path
      end
  rescue URI::InvalidURIError
    session[:return_to] = root_path
  end
end

app/controllers/users/tokens_controller.rb
# frozen_string_literal: true

require 'date'

class Users::TokensController < ApplicationController
  before_action :authenticate_user!, only: :create

  def current_user_token
    token_args = {
      authorizable: current_user, scope: Token::API
    }
    Token.find_or_create_by(token_args) do |token|
      token.token = SecureRandom.hex(32)
      token.contact_email = current_user.email
      token.description = "#{current_user.uid} personal api token"
    end
  end

  def flash_message(token, as_of)
    if token.persisted?
      newly_created = as_of <= token.created_at
      newly_created ? 'Successfully created API token.' : 'Request help to refresh API token.'
    else
      token.errors.full_messages.to_sentence
    end
  end

  def set_flash!(as_of, token)
    flash_type = token.persisted? ? :success : :error
    flash_msg = flash_message(token, as_of)
    flash[flash_type] = flash_msg
  end

  def create
    as_of = DateTime.now

    token = current_user_token
    http_status = token.persisted? ? 200 : 500

    respond_to do |f|
      f.html do
        set_flash!(as_of, token)
        redirect_to account_path
      end
      f.json { render json: { message: flash_message(token, as_of) }.to_json, status: http_status }
    end
  end
end

app/views/user/account.html.erb
<% title 'My Account' %>

<h3>Participation Agreement</h3>
<p>
  <%= render 'uploads/agreement' %>
</p>

<h3>Email Preferences</h3>
<p>
  We send you emails when one of your works is first published in Academic
  Commons. We also send a monthly email with statistics on downloads and views
  for your works. Occasionally we may send other notifications about Academic Commons.
</p>
<p>
  You can change your Academic Commons email preferences below.
</p>

<%= form_with model: @email_preference, url: admin_email_preference_path(@email_preference, format: :json), method: :patch, class: 'form-horizontal ajax-flash-messages', local: false do |f| %>

  <div class="form-group">
    <%= f.label :email, 'Preferred Email', class: 'control-label' %>
    <%= f.text_field :email, class: 'form-control' %>
    <% if @email_preference.email.blank? %>
      <span class="help-block">If a preferred email is not provided, the following email will be used: <%= "#{@email_preference.uni}@columbia.edu" %></span>
    <% end %>
  </div>

  <div class="form-check">
    <%= f.check_box :unsubscribe, class: 'form-check-input' %>
    <%= f.label :unsubscribe, 'Unsubscribe from all emails', class: 'form-check-label' %>
  </div>

  <br>

  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' } %>
  </div>
<% end %>
<h3>API Token</h3>
<%= form_with model: @user_api_token, url: user_token_path(current_user), method: :post, class: 'form-horizontal ajax-flash-messages', local: true do |f| %>
  <% if @user_api_token.new_record? %>
    <div class="form-group">
      <%= f.submit 'Generate Token', class: 'btn btn-primary', data: { disable_with: 'Generating...' } %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :token, 'Personal API Token', class: 'control-label' %>
      <%= f.text_field :token, class: 'form-control', disabled: true %>
    </div>
  <% end %>
<% end %>

app/views/user/all.html.erb
<div>
    <p>All users:</p>
    <% @users.each do |user| %>
        <p>User # <%= user.id %></p>
        <p><%= user.first_name %>
        <p><%= user.email %>
        <p>Provider: <%= user.provider %>
    <% end%>
</div>

app/views/user/my_works.html.erb
<% title 'My Works' %>

<% unless @pending_works.empty? %>
  <h3>Pending Works</h3>
  <table class="table small" data-testid="pending-works-table">
  <% @pending_works.each do |document| %>
    <tr>
      <td><%= document.title %></td>
    </tr>
  <% end %>
  </table>
<% end %>

<% unless @embargoed_works.docs.empty? %>
  <h3>Embargoed Works</h3>
  <table class="table small">
  <% @embargoed_works.docs.each do |document| %>
    <tr>
      <td><%= link_to document.title, solr_document_path(document.id) %></td>
    </tr>
  <% end %>
  </table>
<% end %>

<% if @current_works_with_stats.empty? %>
  <h3>Available Works</h3>
  <h4>No works available </h4>
  <% if deposits_enabled? %>
    <p>Visit our <%= link_to 'upload page', uploads_path %> to contribute your works.</p>
  <% end %>
<% else %>
  <table class="table">
    <tr>
      <th class="header">
        <h3>Available Works</h3>
      </th>
      <th class="header center" colspan="2">
        <h3>Downloads</h3>
      </th>
      <th class="header center" colspan="2">
        <h3>Views</h3>
      </th>
    </tr>
    <tr>
      <th>
        Work
      </th>
      <th class="center">
        <%= @current_works_with_stats.time_period %>
      </th>
      <th class="center">
        Lifetime
      </th>
      <th class="center">
        <%= @current_works_with_stats.time_period %>
      </th>
      <th class="center">
        Lifetime
      </th>
    </tr>
    <% @current_works_with_stats.each do |item_stats| %>
      <% document = item_stats.document %>
        <tr>
          <td>
            <%= link_to document.title, solr_document_path(document.id) %>
          </td>
          <td class="center">
            <%= item_stats.get_stat(Statistic::DOWNLOAD, AcademicCommons::Metrics::PERIOD) %>
          </td>
          <td class="center">
            <%= item_stats.get_stat(Statistic::DOWNLOAD, AcademicCommons::Metrics::LIFETIME) %>
          </td>
          <td class="center">
            <%= item_stats.get_stat(Statistic::VIEW, AcademicCommons::Metrics::PERIOD) %>
          </td>
          <td class="center">
            <%= item_stats.get_stat(Statistic::VIEW, AcademicCommons::Metrics::LIFETIME) %>
          </td>
        </tr>
    <% end %>
    <tr>
      <td>
        <em>Totals:</em>
      </td>
      <td class="center">
        <%= @current_works_with_stats.total_for(Statistic::DOWNLOAD, AcademicCommons::Metrics::PERIOD) %>
      </td>
      <td class="center">
        <%= @current_works_with_stats.total_for(Statistic::DOWNLOAD, AcademicCommons::Metrics::LIFETIME) %>
      </td>
      <td class="center">
        <%= @current_works_with_stats.total_for(Statistic::VIEW, AcademicCommons::Metrics::PERIOD) %>
      </td>
      <td class="center">
        <%= @current_works_with_stats.total_for(Statistic::VIEW, AcademicCommons::Metrics::LIFETIME) %>
      </td>
    </tr>
  </table>
<% end %>