config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # temporarily removing range slider
  # concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new

  # Create the sign in and sign out routes (simply redirects to our auth endpoint), needed for redirecting on
  # cancancan access denied error
  devise_scope :user do
    delete 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "catalog#home"

  # Static Pages
  get '/about',      to: 'info#about',      as: 'about'
  get '/policies',   to: 'info#policies',   as: 'policies'
  get '/faq',        to: 'info#faq',        as: 'faq'
  get '/developers', to: 'info#developers', as: 'developers'
  get '/credits',    to: 'info#credits',    as: 'credits'

  # Mounting API endpoint at /api/v1/
  mount API => '/'

  # Collections routes
  resources :collections, only: [:index, :show], param: 'category_id', path: 'explore'

  # Blacklight routes
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  # Use singular resource with custom collection route to achieve:
  #   search_catalog_url = GET|POST /search |-> catalog#index
  resource :catalog, only: [], as: 'catalog', path: 'search', controller: 'catalog', constraints: { id: /.*/ } do
    collection do
      get '', action: :index
    end
    concerns :searchable
    # concerns :range_searchable
  end

  # OAI endpoint
  match :oai, to: 'catalog#oai', via: [:post, :get], as: :oai_catalog

  # Redirect for old download links
  get '/download/fedora_content/download/:uri/:block/:filename', to: 'assets#legacy_fedora_content', as: 'legacy_fedora_content',
    block: /(CONTENT|content)/, uri: /.+/, filename: /.+/

  # Routes for Solr Document using DOI as identifier
  #
  # Instead of specifying solr routes as:
  #   resources :solr_document, only: [:show], controller: 'catalog', path: 'doi', constraints: { id: /.*/ } do
  #     concerns :exportable
  #   end
  # Specifying routes using glob (*) in id param, this way slashes and period are accepted as part of the id.
  match 'doi/*id/download', to: 'assets#download', via: :get, as: 'content_download'
  match 'doi/*id/embed',    to: 'assets#embed',    via: :get, as: 'embed'
  match 'doi/*id/captions', to: 'assets#captions', via: :get, as: 'captions_download'
  match 'doi/*id',          to: 'catalog#show',    via: :get, as: :solr_document

  mount Blacklight::Engine => '/'

  # RESTful routes for reindex API, working around Blacklight route camping
  delete '/solr_documents/:id', to: 'solr_documents#destroy'
  put '/solr_documents/:id', to: 'solr_documents#update'
  get '/solr_documents/:id', to: 'solr_documents#show'

  resource :agreement

  resources :uploads, only: [:index, :new, :create], path: 'upload'

  get '/detail/:slug', to: 'featured_searches#show', as: 'featured_search'

  get 'myworks',             to: 'user#my_works'
  get 'account',             to: 'user#account'
  get 'unsubscribe_monthly', to: 'user#unsubscribe_monthly'

  get '/admin',                   to: 'admin#index',                 as: 'admin'

  namespace :admin do
    get 'author_affiliation_report/index'
    get 'author_affiliation_report/create'
    resources :request_agreements,  only: [:new, :create]
    resource  :alert_message,       only: [:edit, :update]
    resource  :site_configuration,  only: [:edit, :update]
    resources :deposits,            only: [:index, :show]
    resources :downloads,           only: :index
    resources :agreements,          only: :index
    resources :email_preferences
    resources :email_author_reports,     only: [:new, :create]
    resources :usage_statistics_reports, only: [:new, :create] do
      post 'email', on: :collection
    end
    resources :featured_searches, except: :show
    resource :contact_authors, only: [:new, :create]
  end

  # Resque web interface, only administrators have access
  # Make sure that the resque user restriction below is AFTER `devise_for :users`
  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: '/admin/resque'
  end

  get '/logs/all_author_monthly_reports_history', to: 'logs#all_author_monthly_reports_history'
  get '/logs/log_form',                           to: 'logs#log_form'
  get '/logs/ingest_history',                     to: 'logs#ingest_history'
  get '/download/download_log/:id',               to: 'logs#download_log', as: 'download_log'

  # Route used to render error page.
  get '/500', to: 'errors#internal_server_error'

  # Handle server redirects to /item/:id. This route will redirect those requests
  # to /catalog/:id.
  get '/item/:id',    to: 'catalog#legacy_show'
  get '/catalog/:id', to: 'catalog#legacy_show'

  # Temporary redirect for old deposit page url
  get '/deposit', to: redirect('/upload')
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about; end
  def policies; end
  def faq; end
  def developers; end
  def credits; end
end

app/views/info/about.html.erb
<% title 'About' %>

<% content_for :header do %>
  <h1>About</h1>
<% end %>

<p class="summary">
  Academic Commons provides open, persistent access to the scholarship produced by researchers at Columbia University, Barnard College, Jewish Theological Seminary, Teachers College, and Union Theological Seminary. Academic Commons is a program of the <a href="http://library.columbia.edu/">Columbia University Libraries</a>.
</p>

<h3>Long-term access</h3>
<p>No matter where you live, you can download the full text of the research and scholarship available in Academic Commons without encountering firewalls or fees. If you are a member of the Columbia community, you can upload your work to Academic Commons to ensure that it is accessible for years to come in the digital collections of Columbia University Libraries.</p>

<h3>Enhanced discoverability</h3>
<p>Academic Commons is indexed by leading search engines, metadata aggregators, the Columbia Libraries catalog, and the Columbia University website.</p>

<h3>Citation and attribution</h3>
<p>Items uploaded to Academic Commons receive a <a href="http://www.doi.org">Digital Object Identifier</a>, or DOI, a persistent URL that facilitates citation and attribution.</p>

<h3>Highlighting centers, departments and programs</h3>
<p>Columbia departments, centers, institutes and programs can use Academic Commons to showcase affiliated research, from working papers, reports, and books to conference proceedings and student theses.</p> 
<p>Learn more about having this work appear on your center’s or department’s website using the <%= link_to 'Academic Commons API', developers_path(anchor: 'api') %>.</p>

<p><em>For information about contributing to Academic Commons, visit the <%= link_to t('blacklight.header_links.policies'), policies_path %> and <%= link_to t('blacklight.header_links.faq'), faq_path %> pages.</em></p>

<h3>Open-source technology</h3>
<p>Academic Commons runs on open-source applications including Fedora, the repository platform, and Blacklight, the user interface framework. Columbia University Libraries actively contributes to the development of both platforms. The Academic Commons technology stack includes:</p>

<ul class="brand-logos">
  <li><a href="http://www.fedora-commons.org/"><img src="<%= vite_asset_path('images/brand-logos/logo-fedora.png'); %>" alt="Fedora"><span class="visually-hidden">Fedora</span></a></li>
  <li><a href="http://projectblacklight.org/"><img src="<%= vite_asset_path('images/brand-logos/logo-blacklight.png'); %>" alt="Blacklight"><span class="visually-hidden">Blacklight</span></a></li>
  <li><a href="https://www.mysql.com/"><img src="<%= vite_asset_path('images/brand-logos/logo-mysql.png'); %>" alt="MySQL"><span class="visually-hidden">MySQL</span></a></li>
  <li><a href="https://lucene.apache.org/solr/"><img src="<%= vite_asset_path('images/brand-logos/logo-solr.png'); %>" alt="Apache Solr"><span class="visually-hidden">Apache Solr</span></a></li>
</ul>

<h3>Contributing to a network of open scholarly resources</h3>
<p>Academic Commons is part of a network of initiatives that promote the open distribution of scholarship and research.</p>

<ul class="brand-logos">
    <li><a href="https://www.base-search.net/"><img src="<%= vite_asset_path('images/brand-logos/logo-base-search.png'); %>" alt="BASE"><span class="visually-hidden">BASE</span></a></li>
    <li><a href="https://www.coar-repositories.org/"><img src="<%= vite_asset_path('images/brand-logos/logo-coar.png'); %>" alt="COAR"><span class="visually-hidden">COAR</span></a></li>
    <li><a href="https://core.ac.uk/"><img src="<%= vite_asset_path('images/brand-logos/logo-core.png'); %>" alt="CORE"><span class="visually-hidden">CORE</span></a></li>
    <li><a href="https://www.datacite.org/"><img src="<%= vite_asset_path('images/brand-logos/logo-datacite.png'); %>" alt="Datacite"><span class="visually-hidden">Datacite</span></a></li>
    <li><a href="https://datadryad.org/stash"><img src="<%= vite_asset_path('images/brand-logos/logo-dryad.png'); %>" alt="Dryad"><span class="visually-hidden">Dryad</span></a></li> 
    <li><a href="https://oatd.org/"><img src="<%= vite_asset_path('images/brand-logos/logo-oatd.png'); %>" alt="Open Access Theses and Dissertations"><span class="visually-hidden">Open Access Theses and Dissertations</span></a></li> 
    <li><a href="https://www.re3data.org/"><img src="<%= vite_asset_path('images/brand-logos/logo-re3data.png'); %>" alt="re3data"><span class="visually-hidden">re3data</span></a></li>
    <li><a href="https://unpaywall.org/"><img src="<%= vite_asset_path('images/brand-logos/logo-unpaywall.png'); %>" alt="Unpaywall"><span class="visually-hidden">Unpaywall</span></a></li>
</ul>

<h2 id="learn-more">Learn More</h2>

<div class="row menu">
  <div class="col-md-4 tile">
    <h2><%= link_to t('blacklight.header_links.policies'), policies_path %></h2>
    <p>Read our Collection, Terms of Use, Copyright, and Data Protection policies.</p>
  </div>
  <div class="col-md-4 tile">
    <h2><%= link_to t('blacklight.header_links.faq'), faq_path %></h2>
    <p>View answers to frequently asked questions about Academic Commons, including how to contribute to the repository.</p>
  </div>
  <div class="col-md-4 tile">
    <h2><%= link_to t('blacklight.header_links.developers'), developers_path %></h2>
    <p>Learn about the Academic Commons API, OAI-PMH, SWORD, sitemap, and metadata license.</p>
  </div>
  <div class="col-md-4 tile">
    <h2><%= link_to t('blacklight.header_links.credits'), credits_path %></h2>
    <p>Academic Commons is a team effort. Learn who keeps our repository program running.</p>
  </div>
</div>

app/views/info/api.html.erb
<div id="static-text">
  <div class="page-title">
    <div class="container">
      <h1>API</h1>
    </div>
  </div>

  <div class="container">

  </div><!--.container-->

</div><!--#static-text-->

app/views/info/credits.html.erb
<% title 'Credits' %>

<% content_for :header do %>
  <h1>Credits</h1>
<% end %>

<p class="summary">
  Academic Commons is a program of the Columbia University Libraries.
</p>

<h2>Core team</h2>
<p>
  <strong>Ben Armintor</strong>, Director, Digital Library and Scholarly Technologies<br>
  <strong>Jack Donovan</strong>, Lead Applications Developer<br>
  <strong>Bradley Goldsmith</strong>, Assistant Programmer/Analyst<br>
  <strong>Esther Jackson</strong>, Head, Open Scholarship Services<br>
  <strong>Ed Madrid</strong>, Web Designer<br>
  <strong>Eric O'Hanlon</strong>, Head, Development Infrastructure & Applications<br>
  <strong>Kathryn Pope</strong>, Digital Repository Manager<br>
</p>

<h2>Contributors and Former Team Members</h2>
<p>Nicky Agate, Will Anderson, Anne Cong-Huyen, Eva Cunningham, Stephen Davis, Fred Duby, Carla Galarza, Rob Hilliker, Sarah Holstead, Rebecca Kennison, Brian Luna Lucero, Jeremiah Mercurio, Mark Newton, Amy Nurnberger, Kerri O’Connell, Aleksey Polkalyukhin, Tony Pulickal, Simone Sacchi, Melanie Wacker, Nathan Walker, Leyla Williams</p>

<p><em>Staff from across the Libraries contribute to the development and maintenance of the repository program. We welcome feedback at <a href="mailto:ac@columbia.edu">ac@columbia.edu</a>.</em></p>

app/views/info/developers.html.erb
<% title 'Developer Resources' %>

<% content_for :header do %>
  <h1>Developer Resources</h1>
<% end %>

<% content_for :sidebar do %>
  <ul class="anchor-links" id="sidebar">
      <li><%= link_to 'API', '#api', class:'scroll' %></li>
      <li><%= link_to 'OAI-PMH', '#oai', class:'scroll' %></li>
      <li><%= link_to 'SWORD', '#sword', class:'scroll' %></li>
      <li><%= link_to 'Web Crawlers', '#crawlers', class:'scroll' %></li>
      <li><%= link_to 'Sitemap', '#sitemap', class:'scroll' %></li>
      <li><%= link_to 'Metadata License', '#metadata_license', class:'scroll' %></li>
  </ul>
<% end %>

<h2 id="api">API</h2>
<p>The Academic Commons RESTful API can be used to query/search for records. We support JSON responses. Documentation and a GUI can be found at:<br>
<%= link_to nil, "http://petstore.swagger.io/?url=#{root_url}api/v1/swagger_doc" %></p>
<p>Note that data feeds (data_feed) provide bulk, unpaginated access to a previously-defined subset of records from the API. Data feeds are not API alternatives unless the requestor is a Columbia entity that regularly crawls all of the responses to a consistent query. For example, a specific department name or genre type. To access the data_feed functionality of the API, please contact us at <a href="mailto:ac@columbia.edu">ac@columbia.edu</a>. </p>
<p>The API supports GET requests; users interested in making POST requests should consider using the SWORD protocol detailed below.</p>
<p>To see an example of an AC API integration, visit <a href="https://people.climate.columbia.edu/users/profile/ruth-s-defries">Dr. Ruth S. DeFries's profile</a> in the <a href="https://www.earth.columbia.edu/users">Earth Institute Directory</a>.</p>
<p>For questions about how to integrate an API feed into your Columbia Site, please contact <a href="mailto:ac@columbia.edu">ac@columbia.edu</a>.</p>

<h2 id="oai">OAI-PMH</h2>
<p>Academic Commons supports the <a href="https://www.openarchives.org/OAI/openarchivesprotocol.html">Open Archives Initiative Protocol for Metadata Harvesting (OAI-PMH)</a>, version 2.0.
The base URL is: <%= link_to oai_catalog_url, oai_catalog_url %></p>
<p>Because of strategies employed to combat excessive bot traffic to this website, in order to utilize our OAI-PMH endpoint you may need to work with us to set up a custom user agent. Please email <a href="mailto:ac@columbia.edu">ac@columbia.edu</a> to discuss this approach.</p>

<h2 id="sword">SWORD</h2>
<p>Academic Commons can receive materials via <a href="http://swordapp.org/">SWORD deposit</a>. SWORD is a protocol that automates the deposit process. SWORD is best used for recurring deposits, such as regular deposits of theses or working papers from Columbia departments and regular deposits of articles from Columbia-affiliated journals. Additionally, while the Academic Commons API does not include POST functionality, SWORD can be used in a similar manner to make deposits to Academic Commons in a more programmatic way.</p>

<p>To use SWORD you must have:</p>

<ul>
    <li>SWORD credentials (provided by Columbia Libraries)</li>
        <ul>
            <li>Username and password to use for Basic Authentication header in POST request</li>
            <li>URL to use for the POST request</li>
        </ul>
</ul>
<ul>
    <li>Deposits in package format that include an item (often a PDF) and an xml metadata file</li>
        <ul>
        <li>The SWORD server expects a file in zip format. This zip file will contain the item(s) to be deposited, along with a file called mets.xml. This file will contain metadata, including the list of item files. It is based on Metadata Encoding and Transmission Standard (METS). <%= link_to "View an xml example", "/sample_sword.xml" %>.</li>
        </ul>
</ul>
<ul>
    <li>The ability to create metadata xml files either manually or programmatically</li>
</ul>
<ul>    
    <li>Access to a SWORD client or SWORD library and the ability to initiate deposits</li>
</ul>

<p>If you would like to learn more about how to deposit content via SWORD or start the process of requesting credentials, contact us at <a href="mailto:ac@columbia.edu">ac@columbia.edu</a>.</p> 

<h2 id="crawlers">Web Crawlers</h2>
<p>Aggressive automated crawling of Academic Commons is not permitted, and IP addresses and ranges that exceed a reasonable rate of requests will be blocked. Entities that indiscriminately consume our computational resources create access issues for everyone else, and this behavior is not something that we will accommodate. If you would like to learn more about our rate limits, please email <a href="mailto:ac@columbia.edu">ac@columbia.edu</a>.</p>
<p>Crawling, downloading, or otherwise accessing and/or storing content from Academic Commons for the purposes of training commercial Large Language Models (LLMs) or supplementing commercial Retrieval-Augmented Generation (RAG) systems is not permitted. The use of bibliographic metadata (without abstract text, for which we do not hold the copyright) may be used for this purpose unless a user-agent has been expressly disallowed through our site’s robots.txt.</p>

<h2 id="sitemap">Sitemap</h2>
<p>The sitemap for Academic Commons is regenerated every weekday. <%= link_to nil, "#{root_url}/sitemaps/sitemap.xml.gz" %></p>

<h2 id="metadata_license">Metadata License</h2>
<p>Academic Commons bibliographic metadata—excluding abstracts, which may be under copyright—is available under a <a href="https://creativecommons.org/publicdomain/zero/1.0/">Creative Commons 0 1.0 Universal</a> license.</p>

<p class="small-images">
  <a href="https://creativecommons.org/publicdomain/zero/1.0/">
    <%= cc_img_tag :cc %>
    <%= cc_img_tag :zero %>
  </a>
</p>

<p>To the extent possible under law, Columbia University Libraries has waived all copyright and related or neighboring rights to Academic Commons bibliographic metadata (abstracts are excluded from this license). This work is published from: United States.</p>